from rich.console import Console
from rich.table import Table

console = Console()

console.print("")

table = Table(title="Lista", title_justify="center", title_style="bold green")
table.add_column("[bold green]Comando", style="code", no_wrap=False)
table.add_column("[bold green]Descripción", style="code", no_wrap=False)
table.add_column("[bold green]Estado", style="code", no_wrap=False)

table.add_row("[code]Sistema", style="bold green")
table.add_row("")
table.add_row("• reload", "Recargar el banner", "🔐 Sistema")
table.add_row("• user-config", "Personaliza la interfaz y tu perfíl Stellar", "🔐 Sistema")
table.add_row("• my", "Visualiza tu perfil de Stellar", "🔐 Sistema")
table.add_row("• uninstall", "Desinstala Stellar", "🔐 Sistema")
table.add_row("• update", "Actualiza desde el repositorio de github", "🔐 Sistema")
table.add_row("• reinstall", "Reinstala Stellar en tu termux", "🔐 Sistema")
table.add_row("• bash", "Reinicia su sesión de la terminal", "🔐 Sistema")
table.add_row("• reset", "Reestablece la terminal", "🔐 Sistema")
table.add_row("• tor-enable", "Activa la protección TOR", "🔐 Sistema")
table.add_row("• tor-disable", "Desactiva la protección TOR", "🔐 Sistema")
table.add_row("• banner-enable", "Activa el banner Stellar", "🔐 Sistema")
table.add_row("• banner-disable", "Desactiva el banner Stellar", "🔐 Sistema")

table.add_row("")
table.add_row("[code]Utilidades", style="bold green")
table.add_row("")
table.add_row("• ia", "Un servicio de IA desde OpenAI y Gemini", "🟡 ¡Pronto!")
table.add_row("• ia-image", "Generador de imágenes IA", "🟡 ¡Pronto!")
table.add_row("• traductor", "Traducción en tiempo real", "🟡 ¡Pronto!")
table.add_row("• myip", "Muestra tu IP real", "🟢 Activo")
table.add_row("• passwordgen", "Genera contraseñas seguras para usar", "🟢 Activo")
table.add_row("• encrypt-file", "Encripta archivos", "🟢 Activo")
table.add_row("• ddos", "DDoS en NodeJS para pruebas y ataques", "🟠 Inestable")

table.add_row("")
table.add_row("[code]Discord", style="bold green")
table.add_row("")
table.add_row("• weebhook-mass-spam", "Envia mensajes a un canal de forma masiva", "🟢 Activo")
table.add_row("• mass-delete-channels", "Elimina de forma masiva canales", "🟢 Activo")

table.add_row("")
table.add_row("[code]Osint", style="bold green")
table.add_row("")
table.add_row("• ipinfo", "Obtiene información de una IP", "🟢 Activo") 
table.add_row("• urlinfo", "Analizador de URL", "🟢 Activo")
table.add_row("• userfinder", "Busca un nombre de usuario en el internet", "🟢 Activo")
table.add_row("• phoneinfo", "Obtiene información de un número de teléfono", "🟢 Activo")
table.add_row("• metadatainfo", "Extrae metadatos de imágenes y documentos", "🟢 Activo")
table.add_row("• emailsearch", "Búsqueda de emails", "🟢 Activo")
table.add_row("• instagraminfo", "Obtiene metadatos del perfil", "🟢 Activo")
table.add_row("• whois", "Obtiene información sobre dominios web", "🟡 ¡Pronto!")
table.add_row("• dnslookup", "Consulta registros DNS", "🟡 ¡Pronto!")
table.add_row("• subdomain", "Encuentra subdominios", "🟡 ¡Pronto!")
table.add_row("• virustotal", "Análisis mediante VirusTotal", "🟡 ¡Pronto!")

table.add_row("")
table.add_row("[code]Osint/Discord", style="bold green")
table.add_row("")
table.add_row("• userinfo", "Obtiene información apartir de una ID", "🟢 Activo")
table.add_row("• serverinfo", "Obtiene información sobre un servidor", "🟢 Activo")
table.add_row("• searchinvites", "Busca enlaces de invitación", "🟢 Activo")
table.add_row("• inviteinfo", "Obtiene datos sobre un enlace de invitación", "🟢 Activo")
table.add_row("• role-mapper", "Mapea roles apartir del ID del servidor", "🟢 Activo")
table.add_row("• mutual-servers", "Verifica si hay un servidor común entre usuarios", "🟢 Activo")

console.print(table, style="bright_white", justify="center")
console.print("")